# Generated by Django 6.0 on 2026-01-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideastar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ideastar',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ideastar',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea'),
        ),
        migrations.RemoveField(
            model_name='ideastar',
            name='user',
        ),
    ]
