# Generated by Django 5.2.10 on 2026-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='칼로리'),
        ),
        migrations.AddField(
            model_name='post',
            name='carbs',
            field=models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='지방(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='단백질(g)'),
        ),
    ]
