# Generated by Django 6.0 on 2025-12-31 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moviereview_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('로맨스', '로맨스'), ('코미디', '코미디'), ('드라마', '드라마'), ('멜로', '멜로'), ('SF', 'SF'), ('공포', '공포'), ('스포츠', '스포츠'), ('뮤지컬', '뮤지컬'), ('기타', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='runtime',
            field=models.IntegerField(help_text='분 단위로 입력'),
        ),
    ]
