# Generated by Django 6.0 on 2026-01-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='kind',
            field=models.CharField(max_length=100),
        ),
    ]
