# Generated by Django 6.0 on 2025-12-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
