# Generated by Django 6.0 on 2025-12-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_moviereview_created_at_moviereview_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='created_at',
        ),
    ]
