# Generated by Django 6.0.1 on 2026-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_movie_poster_moviereview_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_name',
            field=models.CharField(default='기타', max_length=100),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='genre_name',
            field=models.CharField(default='기타', max_length=100),
        ),
    ]
