# Generated by Django 6.0.1 on 2026-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_movie_genre_name_moviereview_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='genre_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
